vim.keymap.set('n', '<leader>bd', ':bd!<cr>', { desc = 'Close current buffer' })
vim.keymap.set('', '<leader>rr', ':source %<cr>', { desc = 'Source the current file' })
vim.keymap.set('v', '>', '>gv', { desc = "After tab, re-select" })
vim.keymap.set('v', '<', '<gv', { desc = "After tab, re-select" })
vim.keymap.set('n', 'n', 'nzzzv', { desc = "Go to next search result, and puts the cursor at the middle of the screen" })
vim.keymap.set('n', 'N', 'Nzzzv',
  { desc = "Go to previous search result, and puts the cursor at the middle of the screen" })
vim.keymap.set('n', '<C-s>', ':w<cr>', { desc = "Save current buffer" })
vim.keymap.set('n', '<leader>qq', ':q!<cr>', { desc = "Close window" })
vim.keymap.set('n', '<space><space>x', ':source %<CR>')
vim.keymap.set('n', '<space>x', ':.lua<CR>')
vim.keymap.set('v', '<space>x', '::lua<CR>')
vim.keymap.set('n', '<M-j>', '<cmd>cnext<CR>')
vim.keymap.set('n', '<M-k>', '<cmd>cprev<CR>')
vim.keymap.set('n', '-', '<cmd>Oil<CR>')
vim.keymap.set('n', '<M-q>', '<cmd>bd<CR>')
vim.keymap.set('n', '<M-e>', '<cmd>lua vim.diagnostic.setloclist()<CR>')
vim.keymap.set('n', '<C-j>', '<C-W><C-j>')
vim.keymap.set('n', '<C-k>', '<C-W><C-k>')
vim.keymap.set('n', '<C-l>', '<C-W><C-l>')
vim.keymap.set('n', '<C-h>', '<C-W><C-h>')

vim.keymap.set('n', '<space>st', function()
  vim.cmd.vnew()
  vim.cmd.term()
  vim.cmd.wincmd("J")
  vim.api.nvim_win_set_height(0, 15)
  job_id = vim.bo.channel
end)

-- vim.keymap.set('n', '<space>rt', function()
--   vim.fn.chansend(job_id, { "ls -al\r\n" })
-- end)
