#!/usr/bin/env bash
terminal=$(swaymsg -t get_tree | grep '"app_id": "kittyfixed"')
if [ "$terminal" ]; then
  tmux new-window -t Eduardo
  swaymsg workspace 3
else
  if tmux ls | grep Eduardo; then
    kitty --class kittyfixed tmux attach -tEduardo
  else
    tmux start-server
    kitty --class kittyfixed tmux new-session -sEduardo
  fi
fi
exit 0
